version: '3.9'
services:
    app:
        build: .
        ports:
            - 3000:3000
        environment:
            API_URL: 'http://host.docker.internal:8000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
